In [1]:

import cv2
img=cv2.imread("test2.jpg")
print(img,img[0].size,img.shape)
row,col = img.shape
print(row,col)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 35  51  40]
  [ 36  52  41]
  [ 41  55  44]
  ...
  [ 80  82  90]
  [ 80  82  90]
  [ 81  83  91]]

 [[ 31  47  36]
  [ 33  49  38]
  [ 38  52  41]
  ...
  [ 78  80  88]
  [ 77  79  87]
  [ 76  78  86]]

 [[ 31  45  34]
  [ 31  45  34]
  [ 33  47  36]
  ...
  [ 73  75  83]
  [ 75  77  85]
  [ 76  78  86]]

 ...

 [[ 39  65  52]
  [ 41  69  56]
  [ 47  73  60]
  ...
  [175 180 189]
  [175 180 189]
  [175 180 189]]

 [[ 60  85  71]
  [ 61  87  73]
  [ 64  88  76]
  ...
  [175 180 189]
  [175 180 189]
  [175 180 189]]

 [[ 69  94  80]
  [ 67  92  78]
  [ 67  91  79]
  ...
  [175 180 189]
  [175 180 189]
  [175 180 189]]] 5760 (1080, 1920, 3)


ValueError: too many values to unpack (expected 2)

In [11]:
w=[[1,1,1],
  [1,1,1],
  [1,1,1]]
for i in range(1,row-1):
    for j in range(1,col-1):
        img[i,j]=(w[0][0]*img[i-1][j-1]+w[0][1]*img[i-1][j]+w[0][2]*img[i-1][j+1]+
        w[1][0]*img[i][j-1]+w[1][1]*img[i][j]+w[1][2]*img[i][j+1]+
        w[2][0]*img[i+1][j-1]+w[2][1]*img[i+1][j]+w[2][2]*img[i+1][j+1])/9
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
w=[[-1,-1,-1],
  [-1,8,-1],
  [-1,-1,-1]]
for i in range(1,row-1):
    for j in range(1,col-1):
        img[i,j]=(w[0][0]*img[i-1][j-1]+w[0][1]*img[i-1][j]+w[0][2]*img[i-1][j+1]+
        w[1][0]*img[i][j-1]+w[1][1]*img[i][j]+w[1][2]*img[i][j+1]+
        w[2][0]*img[i+1][j-1]+w[2][1]*img[i+1][j]+w[2][2]*img[i+1][j+1])/9
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import cv2 
import numpy as np 
def contours(image):
    image = cv2.imread('face.jpg')
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edged = cv2.Canny(gray, 30, 200)
    contours, hierarchy = cv2.findContours(edged,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    return contours
# Let's load a simple image with 3 black squares 
image = cv2.imread('face.jpg') 
contour_List = contours(image)

# Finding Contours 
# Use a copy of the image e.g. edged.copy() 
# since findContours alters the image

#print(contour_List)

#cv2.imshow('Canny Edges After Contouring', edged) 
#cv2.waitKey(0) 

print("Number of Contours found = " + str(len(contour_List))) 

# Draw all contours 
# -1 signifies drawing all contours 
cv2.drawContours(image, contour_List, -1, (0, 250, 0), 1) 

cv2.imshow('Contour_List', image) 
cv2.waitKey(0) 
cv2.destroyAllWindows() 


Number of Contours found = 1552


In [12]:
import cv2 
import numpy as np 

def contour(img,orig_img):
    row,column = img.shape
    x=img
    print(row,column)
    for i in range(0,row):
        for j in range(1,column-1):
            
            if ((img[i][j]!=img[i][j-1] and img[i][j]!=img[i][j+1])) or ((img[i][j]==img[i][j-1] and img[i][j]!=img[i][j+1])):
                x[i][j]=255
                orig_img [i][j][0] = 0
                orig_img [i][j][1] = 0
                orig_img [i][j][2] = 255
                orig_img [i][j+1][0] = 0
                orig_img [i][j+1][1] = 0
                orig_img [i][j+1][2] = 255
                
            else:
                x[i][j]=0
    cv2.imshow("contour tracing x",x)
    cv2.imshow("contour tracing original",orig_img)
    cv2.waitKey(0)
    

# Let's load a simple image with 3 black squares 
image = cv2.imread('test.jpeg')  

# Grayscale 
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
(thresh, blackAndWhiteImage) = cv2.threshold(grayImage, 100, 255, cv2.THRESH_BINARY)
print(type(thresh),thresh)
#cv2.imshow('Original image',image)
#cv2.imshow('Gray image', grayImage)
cv2.imshow('Black white image', blackAndWhiteImage)


contour(blackAndWhiteImage,image)

#print(blackAndWhiteImage.shape)

#cv2.waitKey(0)
 
cv2.destroyAllWindows()

<class 'float'> 100.0
668 1000


In [ ]:
#Contour tracing
import goto

def createNBDListCLK(i,j):
    res = [[i,j-1],[i-1,j-1],[i-1,j],[i-1,j+1],[i,j+1],[i+1,j+1],[i+1,j],[i+1,j-1]]
    return res
def createNBDListACLK(i,j):
    res = [[i-1,j],[i-1,j-1],[i,j-1],[i+1,j-1],[i+1,j],[i+1,j+1],[i,j+1],[i-1,j+1]]
    return res
def borderTracing(i,j,i2,j2):
    nbd_positions_clk = createNBDListCLK(i,j)
    for x in nbd_positions_clk:
        if img[x[0]][x[1]]!= 0:
            i1,j1 = x[0],x[1]
        i2,j2 = i1,j1
        i3,j3 = i,j
        #label l1
        nbd_positions_aclk = createNBDListCLK(i3,j3)
        for y in nbd_positions_aclk:
            if img[x[0]][x[1]]!= 0:
                i4,j4 = y[0],y[1]
        if img[i3][j3+1] == 0:
            img[i3][j3] = -NBD
        if (img[i3][j3+1] == 0) and (img[i3][j3] == 1):
            img[i3][j3] = NBD
        if  (i4, j4) == (i, j) and (i3, j3) == (i1, j1):
            return
        else:
            (i2, j2) = (i3, j3)
            (i3, j3) = (i4, j4)
            goto l1
            
    
def contour(image):
    img = image
    row,column = img.shape
    for i in row:
        LNBD = 1
        for j in (1,column):
            if (img[i][j]==1 and img[i][j-1]==0):         #if outer border
                NBD+=1
                i2,j2 = i,j-1
            else if(img[i][j]==1 and img[i][j+1]==0):     #if hole border
                i2,j2 = i,j+1
                if(img[i][j]>1):LNBD = img[i][j]            ##set LNBd to fij if >1
            else:
                if (img[i][j] != 1):
                    LNBD = abs(img[i][j])
                ##go to step3
    cv2.imshow("contour tracing",img)


In [6]:
#Contour tracing #without goto
import cv2
contour_list = []
def createNBDListCLK(i,j):
    res = [[i,j-1],[i-1,j-1],[i-1,j],[i-1,j+1],[i,j+1],[i+1,j+1],[i+1,j],[i+1,j-1]]
    return res
def createNBDListACLK(i,j):
    res = [[i-1,j],[i-1,j-1],[i,j-1],[i+1,j-1],[i+1,j],[i+1,j+1],[i,j+1],[i-1,j+1]]
    return res
def borderTracing(i,j,i2,j2,img,NBD):
    border = []
    border.append((i2,j2))
    nbd_positions_clk = createNBDListCLK(i,j)
    iterator=0
    size=8
    status=True
    flag=0
    while True:
        if status==True:
            while iterator<size:                          #2.1
                x=nbd_positions_clk[iterator]
                iterator=iterator+1
                #print(iterator)
                #print(x[0],x[1],"**")
                if img[x[0]][x[1]]!= 0:           
                    i1,j1 = x[0],x[1]
                    flag=1              
                    i2,j2 = i1,j1                #2.2
                    i3,j3 = i,j
                    if ((i2,j2)not in border):
                        border.append((i2,j2))
        if flag ==0:
            img[i][j]=-NBD
            contour_list.append(border)
            return
        #print(",")
        status=True
        #print(",.")
        nbd_positions_aclk = createNBDListACLK(i3,j3)     #2.3
        #itr=0
        status1=False
        for y in nbd_positions_aclk:
            #y=nbd_positions_aclk[itr]
            if img[y[0]][y[1]]!= 0:
                i4,j4 = y[0],y[1]
                if ((i4,j4)not in border):
                    border.append((i4,j4))
                if img[i3][j3+1] == 0:                       #2.4
                    img[i3][j3] = -NBD
                if (img[i3][j3+1] == 0) and (img[i3][j3] == 1):
                    img[i3][j3] = NBD 
                if  (i3, j3) == (i1, j1) :             #2.5
                    contour_list.append(border)
                    return
                if  (i4, j4) == (i, j):             #2.5
                    contour_list.append(border)
                    return
                    
                else:                              
                    status= False
                    (i2, j2) = (i3, j3)
                    (i3, j3) = (i4, j4)
                    if ((i2,j2)not in border):
                        border.append((i2,j2))
                    nbd_positions_aclk = createNBDListACLK(i3,j3)
                status1 = True
                    #itr = 0
                #itr+=1
        if status1==False:
            contour_list.append(border)
            return
        
def contour(image):
    img = image
    row,column = img.shape
    NBD = 0
    for i in range (1,row-1):
        LNBD = 1
        for j in range(1,column-2):
            if (img[i][j]==1 and img[i][j-1]==0):         #if outer border 1.1
                NBD+=1
                i2,j2 = i,j-1
                borderTracing(i,j,i2,j2,img,NBD)
                if (img[i][j] != 1):
                    LNBD = abs(img[i][j])
            elif((img[i][j]==1) and (img[i][j+1]==0)):     #if hole border 1.2
                i2,j2 = i,j+1
                if(img[i][j]>1):LNBD = img[i][j]            ##set LNBd to fij if >1
                borderTracing(i,j,i2,j2,img,NBD)
                if (img[i][j] != 1):
                    LNBD = abs(img[i][j]) 
            else:                                         #3
                if (img[i][j] != 1):
                    LNBD = abs(img[i][j])
                ##go to step3
    return
# Let's load a simple image with 3 black squares 
image = cv2.imread('test.jpeg')  

# Grayscale 
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
(thresh, blackAndWhiteImage) = cv2.threshold(grayImage, 100, 1, cv2.THRESH_BINARY)
contour(blackAndWhiteImage)
#print(contour_list)

In [11]:
print(len(contour_list))
orig_img1 = cv2.imread("test.jpeg")
f = open("demofile3.txt", "w")
for x in contour_list:
    f.write(str(x))
    for z in x:
        (i,j)=z
        orig_img1 [i][j][0] = 0
        orig_img1 [i][j][1] = 0
        orig_img1 [i][j][2] = 255
f.close()
cv2.imshow("contour tracing original",orig_img1)
cv2.waitKey(0)

43074


-1

In [11]:
i,j=2,3
l1 = [i-1,i,i+1]
l2 = [j-1,j,j+1]
res = [[a,b] for a in l1
             for b in l2 if((a!=i) or (b!=j))]
res1 = [[a,b] for a in l1
             for b in l2 ]
print(res,"****************",res1)

[[1, 2], [1, 3], [1, 4], [2, 2], [2, 4], [3, 2], [3, 3], [3, 4]] **************** [[1, 2], [1, 3], [1, 4], [2, 2], [2, 3], [2, 4], [3, 2], [3, 3], [3, 4]]


In [17]:
x=[1,2,5,255]
z=[i for i in x if (i!=1) or (i!=255)]
print(z)

[1, 2, 5, 255]


In [ ]:
import cv2
import numpy as np
import sys
from os.path import splitext


def crop(image, r, c, height, width):
    return image[r:r+height, c:c+width]


def moore_neighbor_tracing(image, accumulator, maxr):
    color = 100
    original_height, original_width = image.shape
    image = np.pad(image, ((1, 1), (1, 1)), 'constant', constant_values=(255, 255))
    height, width = image.shape
    contour_pixels = []
    p = (0, 0)
    c = (0, 0)
    s = (0, 0)
    previous = (0, 0)
    found = False

    # Find the first point
    for i in range(height):
        for j in range(width):
            if image[i, j] <= color and not (i == 0 and j == 0):
                s = (i, j)
                # contour_pixels.append(s)
                contour_pixels.append((s[0]-1, s[1]-1))
                p = s
                found = True
                break
            if not found:
                previous = (i, j)
        if found:
            break

    # If the pixel is isolated i don't do anything
    isolated = True
    m = moore_neighbor(p)
    for r, c in m:
        if image[r, c] <= color:
            isolated = False

    if not isolated:
        tmp = c
        # Backtrack and next clockwise M(p)
        c = next_neighbor(s, previous)
        previous = tmp
        while c != s:
            if image[c] <= color:
                previous_contour = contour_pixels[len(contour_pixels) - 1]

                # contour_pixels.append(c)
                contour_pixels.append((c[0]-1, c[1]-1))
                p = c
                c = previous

                # HERE is where i have to start checking for lines
                # i get the previous contour pixel
                current_contour = p[0] - 1, p[1] - 1

                # i have to calculate t (between 0 and 179) of the line that connects the two pixel
                t = np.arctan2(previous_contour[1]-current_contour[1], previous_contour[0]-current_contour[0]) * 180 / np.pi
                t = int(np.round(t))
                if t < 0:
                    t += 180
                t %= 180

                # This is the "classic" Hough in which we consider only a subset of all the possible lines
                for t in range(t-30, t+31):
                    if t >= 180:
                        t = 180 - t
                    if t < 0:
                        t = 180 + t
                    rad = np.deg2rad(t)

                    r = current_contour[0] * np.sin(rad) + current_contour[1] * np.cos(rad) + maxr
                    accumulator[int(np.round(r)), t] += 1

            else:
                previous = c
                c = next_neighbor(p, c)

        image = crop(image, 1, 1, original_height, original_width)
    return contour_pixels


def moore_neighbor(pixel):
    row, col = pixel
    return ((row - 1, col - 1), (row - 1, col), (row - 1, col + 1),
            (row, col + 1), (row + 1, col + 1),
            (row + 1, col), (row + 1, col - 1),
            (row, col - 1))


def next_neighbor(central, neighbor):
    neighbors = moore_neighbor(central)
    index = np.where((np.array(neighbors) == neighbor).all(axis=1))[0][0]
    index += 1
    index = index % 8

    # Problem operating like this:
    # if the object of which i want to detect contours starts at the edges of the image there's the possibility
    # of going out of bounds
    return neighbors[index]


# Function that "deletes" an object using the information about its contours
def delete_object(image, contoured, contours):
    # With the edge pixel i also delete its moore neighborhood because otherwise if and edge is 2 pixel thick
    # because i find only the external contour i wouldn't delete the contour completely
    height, width = image.shape
    for x, y in contours:
        image[x, y] = 255
        image[np.clip(x - 1, 0, height - 1), np.clip(y - 1, 0, width - 1)] = 255
        image[np.clip(x - 1, 0, height - 1), y] = 255
        image[np.clip(x - 1, 0, height - 1), np.clip(y + 1, 0, width - 1)] = 255
        image[x, np.clip(y - 1, 0, width - 1)] = 255
        image[x, y] = 255
        image[x, np.clip(y + 1, 0, width - 1)] = 255
        image[np.clip(x + 1, 0, height - 1), np.clip(y - 1, 0, width - 1)] = 255
        image[np.clip(x + 1, 0, height - 1), y] = 255
        image[np.clip(x + 1, 0, height - 1), np.clip(y + 1, 0, width - 1)] = 255

    return image


# INPUT PARAMETER: a binarized image (using Canny edge) in which the contours are black and the background is white
# OUTPUT PARAMETER: an image with black background and white contours for all the objects identified and red lines
#                   where they are found
# Used later to save the image
image_basename = 'face'
img_format = "jpg"

# Load the image
image = cv2.imread("face.jpg",0)
contour_all = np.zeros(image.shape, np.uint8)

height, width = image.shape
# Variables used to perform hough
maxr = int(np.ceil(np.sqrt(np.power(height, 2) + np.power(width, 2))))
accumulator = np.zeros((maxr * 2 + 1, 180), np.uint32)

# I iterate until there are no more edge pixels
# I keep tracing contours updating the accumulator matrix
# delete the contour found and repeat
while np.any(image <= 100):
    contoured = np.zeros(image.shape, np.uint8)
    contours = moore_neighbor_tracing(image, accumulator, maxr)
    for x, y in contours:
        contoured[x, y] = 255
        contour_all[x, y] = 255
    delete_object(image, contoured, contours)

cv2.imshow("aaf", contour_all)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite(image_basename + "_contoured" + img_format, contour_all)




In [2]:
x= []
x.append((2,3))
print(x)

[(2, 3)]


In [10]:
import cv2
def spiralstoring(m, n, a) : 
    encodedStringInt=""
    k = 0; l = 0
  
    ''' k - starting row index 
        m - ending row index 
        l - starting column index 
        n - ending column index 
        i - iterator '''
      
  
    while (k < m and l < n) : 
          
        # Print the first row from 
        # the remaining rows  
        for i in range(l, n) :
            x = str(hex(a[k][i]))                                   
            encodedStringInt=encodedStringInt+"0"*(2-len(x[2:]))+x[2:] 
            
        k += 1
        # Print the last column from 
        # the remaining columns  
        for i in range(k, m) : 
            x = str(hex(a[i][n - 1]))                                   
            encodedStringInt=encodedStringInt+"0"*(2-len(x[2:]))+x[2:] 
            
        n -= 1
  
        # Print the last row from 
        # the remaining rows  
        if ( k < m) : 
              
            for i in range(n - 1, (l - 1), -1) : 
                x = str(hex(a[m - 1][i]))
                encodedStringInt=encodedStringInt+"0"*(2-len(x[2:]))+x[2:] 
                
            m -= 1
          
        # Print the first column from 
        # the remaining columns  
        if (l < n) : 
            for i in range(m - 1, k - 1, -1) :
                x = str(hex(a[i][l]))                                   
                encodedStringInt=encodedStringInt+"0"*(2-len(x[2:]))+x[2:] 
              
            l += 1
    return encodedStringInt 
img=cv2.imread("test2.jpg")
grayImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#print(img,img[0].size,img.shape)
row,col = grayImage.shape
x = spiralstoring(row,col,grayImage)
f = open("colorencoding.txt","w")
f.write(x)
f.close()
#print(x)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [11]:
img=cv2.imread("face.jpg")
grayImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(grayImage)

[[ 61  66  59 ...  64  64  64]
 [ 59  62  73 ...  65  65  65]
 [ 74  57  43 ...  61  61  61]
 ...
 [240 240 240 ... 239 241  97]
 [240 240 240 ... 239 240  96]
 [240 240 240 ... 239 240  95]]
